name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
tag-prefix: 'v'
commitish: main

categories:
  - title: Features
    label: feature
  - title: Fixes
    label: fix
  - title: Chores
    label: chore

exclude-labels:
  - skip-changelog

change-template: '- $TITLE (#$NUMBER) @$AUTHOR'
change-title-escapes: '\<*_&'
no-changes-template: '- No changes'
category-template: '### $TITLE'

version-resolver:
  major:
    labels:
      - major
  minor:
    labels:
      - minor
  patch:
    labels:
      - patch
  default: patch

template: |
  ## Changes

  $CHANGES

  ## Contributors

  $CONTRIBUTORS
